version: 2
jobs:
  build_and_deploy:
    environment:
      APP_NAME: arrangement-app
      ECR_ENDPOINT: 882089634282.dkr.ecr.eu-central-1.amazonaws.com
      AWS_DEFAULT_REGION: eu-central-1
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - deploy:
          name: Push application Docker image
          command: |
            if [[ "$CIRCLE_TAG" = "" ]]; then #if there is no git tag
              login="$(aws ecr get-login)"
              ${login}
              echo "pushing latest"
              docker tag app "${ECR_ENDPOINT}/${APP_NAME}:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/${APP_NAME}:${CIRCLE_SHA1}"
            elif [ -n "$CIRCLE_TAG" ]; then
              login="$(aws ecr get-login)"
              ${login}
              echo "pushing tag ${ECR_ENDPOINT}/${APP_NAME}:${CIRCLE_TAG}"              
              docker tag app "${ECR_ENDPOINT}/${APP_NAME}:${CIRCLE_TAG}"
              docker push "${ECR_ENDPOINT}/${APP_NAME}:${CIRCLE_TAG}"
            fi
  create_task_definition:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - run:
          name: Register task definition
          command: |
            cd .circleci/CloudAutomation/
            npm install
            node aws-robot.js
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - create_task_definition:
          requires:
            - build_and_deploy
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
