name: Build and deploy arrangement-app to prod

on:
  release:
    types:
      - released

jobs:
  build:
    name: Build and push docker image
    uses: bekk/bekk-ci-workflows/.github/workflows/build.yml@master
    with:
      ENVIRONMENT: production
      IMAGE_TAG: ${{ github.event.release.tag_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    name: Deploy arrangement-app to prod
    uses: bekk/bekk-ci-workflows/.github/workflows/deploy.yml@master
    needs: build
    with:
      ENVIRONMENT: production
      IMAGE_NAME: ${{ needs.build.outputs.image_name }}
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
      TERRAFORM_WORKSPACE: prod
      TERRAFORM_VAR_FILE: prod.tfvars
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
